# Generated by Django 5.2.17 on 2026-09-14 12:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(choices=[('building', 'Facilities'), ('users', 'Library Staff'), ('wifi', 'Internet/Wi-Fi'), ('monitor', 'Computer Services'), ('book-open', 'Borrowing & Returning'), ('layout', 'Study Areas'), ('globe', 'Online Resources'), ('help-circle', 'Other')], default='help-circle', help_text='Line-style icon identifier used by the service icon partial.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Library Service',
                'verbose_name_plural': 'Library Services',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')])),
                ('sentiment', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative')], editable=False, help_text='Auto-derived from rating on save: 4-5=Positive, 3=Neutral, 1-2=Negative.', max_length=10)),
                ('student_type', models.CharField(choices=[('Undergraduate Student', 'Undergraduate Student'), ('Graduate / Masteral Student', 'Graduate / Masteral Student'), ('Faculty / Instructor', 'Faculty / Instructor'), ('University Administrative Staff', 'University Administrative Staff'), ('Visiting Researcher / Alumni', 'Visiting Researcher / Alumni')], default='Undergraduate Student', max_length=50)),
                ('comment', models.TextField(blank=True, help_text='Optional free-text feedback.')),
                ('action_label', models.CharField(blank=True, default='Under Review', help_text='Administrative action, e.g. Create IT Ticket, ✓ Commended, Work Order Sent.', max_length=60)),
                ('is_action_resolved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='feedback.libraryservice')),
            ],
            options={
                'verbose_name': 'Feedback Log',
                'verbose_name_plural': 'Feedback Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
