# Generated by Django 5.2.17 on 2026-09-20 04:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_seed_library_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Raw free-text feedback, to be scored by the sentiment model.')),
                ('sentiment', models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative')], help_text='Populated once the trained sentiment model is integrated.', max_length=10, null=True)),
                ('confidence', models.FloatField(blank=True, help_text='Model confidence score for the predicted sentiment (0.0-1.0), once available.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Quick Feedback',
                'verbose_name_plural': 'Quick Feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
