# Generated by Django 5.2.17 on 2026-09-20 04:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_quickfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')])),
                ('comment', models.TextField(blank=True, help_text='Free-text feedback, classified by the sentiment model.')),
                ('sentiment', models.CharField(blank=True, choices=[('negative', 'Negative'), ('neutral', 'Neutral'), ('positive', 'Positive')], editable=False, help_text='Predicted by the trained model from `comment` (blank if no comment was given).', max_length=10)),
                ('sentiment_priority', models.PositiveSmallIntegerField(default=1, editable=False, help_text='Sort key derived from sentiment: negative=0, neutral=1, positive=2.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_feedbacks', to='feedback.libraryservice')),
            ],
            options={
                'verbose_name': 'ML Feedback',
                'verbose_name_plural': 'ML Feedback',
                'ordering': ['sentiment_priority', '-created_at'],
            },
        ),
    ]
