# Generated by Django 5.2.17 on 2026-09-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuickFeedback',
        ),
        migrations.AlterField(
            model_name='feedbacklog',
            name='sentiment',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative')], editable=False, help_text='Classified by the trained sentiment model (feedback.ml) from `comment` when one is given; otherwise falls back to rating on save: 4-5=Positive, 3=Neutral, 1-2=Negative.', max_length=10),
        ),
    ]
