# Generated by Django 5.2.17 on 2026-09-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_delete_quickfeedback_alter_feedbacklog_sentiment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbacklog',
            options={'ordering': ['sentiment_priority', '-timestamp'], 'verbose_name': 'Feedback Log', 'verbose_name_plural': 'Feedback Logs'},
        ),
        migrations.RemoveField(
            model_name='feedbacklog',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='feedbacklog',
            name='student_type',
        ),
        migrations.AddField(
            model_name='feedbacklog',
            name='sentiment_priority',
            field=models.PositiveSmallIntegerField(default=1, editable=False, help_text='Sort key derived from sentiment: negative=0, neutral=1, positive=2.'),
        ),
        migrations.AlterField(
            model_name='feedbacklog',
            name='comment',
            field=models.TextField(help_text='Free-text feedback — classified by the trained sentiment model.'),
        ),
        migrations.AlterField(
            model_name='feedbacklog',
            name='sentiment',
            field=models.CharField(choices=[('Negative', 'Negative'), ('Neutral', 'Neutral'), ('Positive', 'Positive')], editable=False, help_text='Classified by the trained sentiment model (feedback.ml) from `comment`.', max_length=10),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
