# Generated by Django 5.2.17 on 2026-10-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_alter_feedbacklog_options_remove_feedbacklog_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacklog',
            name='action_label',
        ),
        migrations.RemoveField(
            model_name='feedbacklog',
            name='is_action_resolved',
        ),
    ]
